Repository milieuinfo/webcomponent-vl-ui-cookie-consent, pull requests merged in 2020-04, with the labels that each got.

#33 Update vl-ui-modal
  package-lock.json
  package.json
Labels: bug

#34 Update vl-ui-modal
  package-lock.json
  package.json
Labels: bug

#32 Introductie dynamische tekst voor eigenaar en privacy link
  demo/vl-cookie-consent-opt-in.html
  demo/vl-cookie-consent.html
  index.js
  package.json
  src/index.js
  src/vl-cookie-consent-all.js
  src/vl-cookie-consent-opt-in.js
  src/vl-cookie-consent.js
  test/e2e/components/vl-cookie-consent-opt-in.js
  test/e2e/components/vl-cookie-consent.js
  test/e2e/cookie-consent-opt-in.test.js
  test/e2e/cookie-consent.test.js
  test/e2e/pages/vl-cookie-consent-opt-in.page.js
  test/e2e/pages/vl-cookie-consent.page.js
  test/unit/vl-cookie-consent.test.html
Labels: enhancement

#36 Update vl-ui-util
  .mocharc.js
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
Labels: chore

#38 Update dependencies en vl-ui-util om foutieve src dist builds op te lossen
  dist/vl-cookie-consent-all.src.js
  dist/vl-cookie-consent.js
  dist/vl-cookie-consent.min.js
  dist/vl-cookie-consent.src.js
  package-lock.json
  package.json
Labels: bug
