Repository milieuinfo/webcomponent-vl-ui-cookie-consent, pull requests merged in 2020-01, with the labels that each got.

#7 Overbodig NPM release import scripts verwijderd
  package.json
Labels: maintenance

#9 Verwijder pretest fase (installeren chromedriver). Deze komt via vl-ui-util binnenDepend op core-branch zonder after
  package.json
Labels: chore

#8 Update vl-ui-util
  README.md
  demo/demo.css
  demo/demo.css.map
  demo/demo.js
  package-lock.json
  package.json
  style.css
  test/docker-compose.yml
Labels: maintenance

#10 Update vl-ui-util
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
  test/docker-compose.yml
Labels: maintenance

#11 Update vl-ui-util
  bamboo-specs/bamboo.yml
  docker-compose-release.yml
  package-lock.json
  package.json
Labels: maintenance

#12 Update vl-ui-util
  package-lock.json
  package.json
Labels: chore

#14 #13: Update naar vl-ui-modal v1.0.19
  demo/demo.css
  demo/demo.css.map
  package-lock.json
  package.json
  style.css.map
  vl-cookie-consent.js
Labels: bug
