Repository milieuinfo/webcomponent-vl-ui-cookie-consent, pull requests merged in 2020-05, with the labels that each got.

#39 Lock file maintenance
  package-lock.json
Labels: chore, dependencies, renovate

#42 Lock file maintenance
  package-lock.json
Labels: chore, dependencies, renovate

#44 Oplossing voor build problemen min variant
  dist/vl-cookie-consent-all.min.js
  dist/vl-cookie-consent.min.js
  package-lock.json
  package.json
Labels: bug

#46 Fix rode build
  .eslintrc.json
  CODEOWNERS
  dist/analytics.js
  dist/index.js
  dist/vl-cookie-consent-all.js
  dist/vl-cookie-consent-all.min.js
  dist/vl-cookie-consent-all.src.js
  dist/vl-cookie-consent-opt-in.js
  dist/vl-cookie-consent-opt-in.min.js
  dist/vl-cookie-consent-opt-in.src.js
  dist/vl-cookie-consent.js
  dist/vl-cookie-consent.min.js
  dist/vl-cookie-consent.src.js
  index.js
  package-lock.json
  package.json
  src/analytics.js
  src/index.js
  src/vl-cookie-consent-all.js
  src/vl-cookie-consent-opt-in.js
  src/vl-cookie-consent.js
  test/e2e/components/cookie-manager.js
  test/e2e/components/vl-cookie-consent-opt-in.js
  test/e2e/components/vl-cookie-consent.js
  test/e2e/cookie-consent-opt-in.test.js
  test/e2e/cookie-consent.test.js
  test/e2e/pages/vl-cookie-consent-opt-in.page.js
  test/e2e/pages/vl-cookie-consent.page.js
  test/unit/vl-cookie-consent.test.html
Labels: bugfix
